### ISSUE TITLE
Splash Screen Stuck on 'Saving Monitor Config to Disk'

### ISSUE THREAD

**Issue by Yendall** [loueradun/GamestreamLauncher#1]
Not sure if this is permission based but the splash screen is stuck on this message

**Comment by loueradun** [comment]
It probably is a permission based issue.  For example copying the launcher to the program files directory causes similar symptoms.

Gamestream is not run with administrator rights, and since the application is portable and doesn't currently use an installer it will have issues writing a file to the disk if the application is copied to a folder in the Program Files directory for example.
